// Runs before `ng build --configuration production` on Vercel.
// Writes src/environments/environment.prod.ts from process.env.
const { writeFileSync } = require('fs');
const { join } = require('path');

const url = process.env['SUPABASE_URL'];
const key = process.env['SUPABASE_ANON_KEY'];

if (!url || !key) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.');
  process.exit(1);
}

const content = `// Generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  supabaseUrl: ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(key)},
};
`;

writeFileSync(join(__dirname, '../src/environments/environment.prod.ts'), content);
console.log('environment.prod.ts written.');
